
# Replace with your Cosmos DB details
PREFERRED_LOCATIONS = []
COSMOS_PROXY_URI = ""
COSMOS_URI = ""
COSMOS_KEY = ""
COSMOS_CONTAINER = ""
COSMOS_DATABASE = ""
USE_MULTIPLE_WRITABLE_LOCATIONS = False
CONCURRENT_REQUESTS = 100