# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import TYPE_CHECKING, Union
from typing_extensions import Required, TypedDict

if TYPE_CHECKING:
    from .models import CommunicationIdentityTokenScope, TeamsExtensionPrincipalType


class CommunicationIdentityAccessTokenRequest(TypedDict, total=False):
    """Request to issue a new access token for an identity.

    :ivar scopes: List of scopes attached to the token. Required.
    :vartype scopes: list[Union[str, "CommunicationIdentityTokenScope"]]
    :ivar expiresInMinutes: Optional custom validity period of the token within [60,1440] minutes
     range. If not provided, the default value of 1440 minutes (24 hours) will be used.
    :vartype expiresInMinutes: int
    """

    scopes: Required[list[Union[str, "CommunicationIdentityTokenScope"]]]
    """List of scopes attached to the token. Required."""
    expiresInMinutes: int
    """Optional custom validity period of the token within [60,1440] minutes range. If not provided,
     the default value of 1440 minutes (24 hours) will be used."""


class CommunicationIdentityCreateRequest(TypedDict, total=False):
    """Request to create a new identity with optional access token.

    :ivar createTokenWithScopes: Also create access token for the created identity.
    :vartype createTokenWithScopes: list[Union[str, "CommunicationIdentityTokenScope"]]
    :ivar expiresInMinutes: Optional custom validity period of the token within [60,1440] minutes
     range. If not provided, the default value of 1440 minutes (24 hours) will be used.
    :vartype expiresInMinutes: int
    """

    createTokenWithScopes: list[Union[str, "CommunicationIdentityTokenScope"]]
    """Also create access token for the created identity."""
    expiresInMinutes: int
    """Optional custom validity period of the token within [60,1440] minutes range. If not provided,
     the default value of 1440 minutes (24 hours) will be used."""


class TeamsExtensionAssignmentCreateOrUpdateRequest(TypedDict, total=False):  # pylint: disable=name-too-long
    """A request to create or update a Teams Extension assignment.

    :ivar principalType: The type of principal the assignment is for. Required. Known values are:
     "resourceAccount" and "user".
    :vartype principalType: Union[str, "TeamsExtensionPrincipalType"]
    :ivar clientIds: The client IDs for the assignment.
    :vartype clientIds: list[str]
    """

    principalType: Required[Union[str, "TeamsExtensionPrincipalType"]]
    """The type of principal the assignment is for. Required. Known values are: \"resourceAccount\"
     and \"user\"."""
    clientIds: list[str]
    """The client IDs for the assignment."""


class TeamsExtensionExchangeTokenRequest(TypedDict, total=False):
    """A request to exchange a Teams Extension token."""


class TeamsUserExchangeTokenRequest(TypedDict, total=False):
    """A request to exchange a Teams user access token.

    :ivar token: Entra ID access token of a Teams User to acquire a new Communication Identity
     access token. Required.
    :vartype token: str
    :ivar appId: Client ID of an Entra ID application to be verified against the appid claim in the
     Entra ID access token. Required.
    :vartype appId: str
    :ivar userId: Object ID of an Entra ID user (Teams User) to be verified against the oid claim
     in the Entra ID access token. Required.
    :vartype userId: str
    """

    token: Required[str]
    """Entra ID access token of a Teams User to acquire a new Communication Identity access token.
     Required."""
    appId: Required[str]
    """Client ID of an Entra ID application to be verified against the appid claim in the Entra ID
     access token. Required."""
    userId: Required[str]
    """Object ID of an Entra ID user (Teams User) to be verified against the oid claim in the Entra ID
     access token. Required."""
