#!/bin/bash
python3 r_w_q_workload.py &
python3 r-w-q-workload-1.py &
python3 r-w-q-workload-2.py &
python3 r_w_q_workload-3.py &
python3 r-w-q-workload-4.py &
python3 r-w-q-workload-5.py &
python3 r-w-q-workload-6.py &
python3 r-w-q-workload-7.py &
python3 r-w-q-workload-8.py &
python3 r-w-q-workload-9.py &
python3 r-w-q-workload-10.py &
python3 r-w-q-workload-11.py &
python3 r-w-q-workload-12.py &
python3 r_w_q_workload-13.py &
python3 r-w-q-workload-14.py &
python3 r-w-q-workload-15.py &
python3 r-w-q-workload-16.py &
python3 r-w-q-workload-17.py &
python3 r-w-q-workload-18.py &
python3 r-w-q-workload-19.py &
python3 r-w-q-workload-20.py &
python3 r_workload.py &
python3 r-workload-1.py &
python3 r-workload-2.py &
python3 r-workload-3.py &
python3 r-workload-4.py &
python3 r-workload-5.py &
python3 r-workload-6.py &
python3 r-workload-7.py &
python3 r-workload-8.py &
python3 r-workload-9.py &
python3 r-workload-10.py &
python3 r-workload-11.py &
python3 r-workload-12.py &
python3 r-workload-13.py &
python3 r-workload-14.py &
python3 r-workload-15.py &
python3 r-workload-16.py &
python3 r-workload-17.py &
python3 r-workload-18.py &
python3 r-workload-19.py &
python3 r-workload-20.py &
python3 w_workload.py &
python3 w-workload-1.py &
python3 w-workload-2.py &
python3 w-workload-3.py &
python3 w-workload-4.py &
python3 w-workload-5.py &
python3 w-workload-6.py &
python3 w-workload-7.py &
python3 w-workload-8.py &
python3 w-workload-9.py &
python3 w-workload-10.py &
python3 w-workload-11.py &
python3 w-workload-12.py &
python3 w-workload-13.py &
python3 w-workload-14.py &
python3 w-workload-15.py &
python3 w-workload-16.py &
python3 w-workload-17.py &
python3 w-workload-18.py &
python3 w-workload-19.py &
python3 w-workload-20.py &
python3 r_w_q_workload_sync.py &
python3 r-w-q-workload-sync-1.py &
