from . import _models_py3
from . import _metrics_advisor_client_enums
from . import _patch

class AlertResultList(_models_py3.AlertResultList):
    ...
class AnomalyAlert(_patch.AnomalyAlert):
    ...
class AnomalyAlertConfiguration(_patch.AnomalyAlertConfiguration):
    ...
class AnomalyAlertingConfigurationList(_models_py3.AnomalyAlertingConfigurationList):
    ...
class AnomalyDetectionConfiguration(_patch.AnomalyDetectionConfiguration):
    ...
class AnomalyDetectionConfigurationList(_models_py3.AnomalyDetectionConfigurationList):
    ...
class AnomalyDimensionList(_models_py3.AnomalyDimensionList):
    ...
class AnomalyFeedback(_patch.AnomalyFeedback):
    ...
class AnomalyIncident(_patch.AnomalyIncident):
    ...
class AnomalyResultList(_models_py3.AnomalyResultList):
    ...
class AzureApplicationInsightsDataFeedSource(_patch.AzureApplicationInsightsDataFeedSource):
    ...
class AzureBlobDataFeedSource(_patch.AzureBlobDataFeedSource):
    ...
class AzureCosmosDbDataFeedSource(_patch.AzureCosmosDbDataFeedSource):
    ...
class AzureDataExplorerDataFeedSource(_patch.AzureDataExplorerDataFeedSource):
    ...
class AzureDataLakeStorageGen2DataFeedSource(_patch.AzureDataLakeStorageGen2DataFeedSource):
    ...
class AzureEventHubsDataFeedSource(_patch.AzureEventHubsDataFeedSource):
    ...
class AzureLogAnalyticsDataFeedSource(_patch.AzureLogAnalyticsDataFeedSource):
    ...
class AzureTableDataFeedSource(_patch.AzureTableDataFeedSource):
    ...
class ChangePointFeedback(_patch.ChangePointFeedback):
    ...
class ChangeThresholdCondition(_patch.ChangeThresholdCondition):
    ...
class CommentFeedback(_patch.CommentFeedback):
    ...
class DataFeed(_patch.DataFeed):
    ...
class DataFeedDimension(_patch.DataFeedDimension):
    ...
class DataFeedIngestionProgress(_patch.DataFeedIngestionProgress):
    ...
class DataFeedIngestionStatus(_models_py3.DataFeedIngestionStatus):
    ...
class DataFeedList(_models_py3.DataFeedList):
    ...
class DataFeedMetric(_patch.DataFeedMetric):
    ...
class DataPointAnomaly(_patch.DataPointAnomaly):
    ...
class DataSourceCredentialList(_models_py3.DataSourceCredentialList):
    ...
class DatasourceCredential(_patch.DatasourceCredential):
    ...
class DatasourceDataLakeGen2SharedKey(_patch.DatasourceDataLakeGen2SharedKey):
    ...
class DatasourceServicePrincipal(_patch.DatasourceServicePrincipal):
    ...
class DatasourceServicePrincipalInKeyVault(_patch.DatasourceServicePrincipalInKeyVault):
    ...
class DatasourceSqlConnectionString(_patch.DatasourceSqlConnectionString):
    ...
class DetectionAnomalyFilterCondition(_patch.DetectionAnomalyFilterCondition):
    ...
class DetectionIncidentFilterCondition(_models_py3.DetectionIncidentFilterCondition):
    ...
class DimensionGroupIdentity(_models_py3.DimensionGroupIdentity):
    ...
class EmailNotificationHook(_patch.EmailNotificationHook):
    ...
class EnrichmentStatus(_models_py3.EnrichmentStatus):
    ...
class EnrichmentStatusList(_models_py3.EnrichmentStatusList):
    ...
class HardThresholdCondition(_patch.HardThresholdCondition):
    ...
class HookList(_models_py3.HookList):
    ...
class IncidentResultList(_models_py3.IncidentResultList):
    ...
class IncidentRootCause(_patch.IncidentRootCause):
    ...
class InfluxDbDataFeedSource(_patch.InfluxDbDataFeedSource):
    ...
class IngestionStatusList(_models_py3.IngestionStatusList):
    ...
class MetricAlertConfiguration(_patch.MetricAlertConfiguration):
    ...
class MetricAnomalyAlertSnoozeCondition(_patch.MetricAnomalyAlertSnoozeCondition):
    ...
class MetricBoundaryCondition(_patch.MetricBoundaryCondition):
    ...
class MetricDataList(_models_py3.MetricDataList):
    ...
class MetricDetectionCondition(_patch.MetricDetectionCondition):
    ...
class MetricDimensionList(_models_py3.MetricDimensionList):
    ...
class MetricEnrichedSeriesData(_patch.MetricEnrichedSeriesData):
    ...
class MetricFeedback(_patch.MetricFeedback):
    ...
class MetricFeedbackList(_models_py3.MetricFeedbackList):
    ...
class MetricSeriesData(_patch.MetricSeriesData):
    ...
class MetricSeriesDefinition(_models_py3.MetricSeriesDefinition):
    ...
class MetricSeriesGroupDetectionCondition(_patch.MetricSeriesGroupDetectionCondition):
    ...
class MetricSeriesList(_models_py3.MetricSeriesList):
    ...
class MetricSingleSeriesDetectionCondition(_patch.MetricSingleSeriesDetectionCondition):
    ...
class MongoDbDataFeedSource(_patch.MongoDbDataFeedSource):
    ...
class NotificationHook(_patch.NotificationHook):
    ...
class PeriodFeedback(_patch.PeriodFeedback):
    ...
class RootCauseList(_models_py3.RootCauseList):
    ...
class SeriesIdentity(_patch.SeriesIdentity):
    ...
class SeriesResultList(_models_py3.SeriesResultList):
    ...
class SeverityCondition(_patch.SeverityCondition):
    ...
class SeverityFilterCondition(_models_py3.SeverityFilterCondition):
    ...
class SmartDetectionCondition(_patch.SmartDetectionCondition):
    ...
class SuppressCondition(_patch.SuppressCondition):
    ...
class TopNGroupScope(_patch.TopNGroupScope):
    ...
class WebNotificationHook(_patch.WebNotificationHook):
    ...
class MySqlDataFeedSource(_patch.MySqlDataFeedSource):
    ...
class PostgreSqlDataFeedSource(_patch.PostgreSqlDataFeedSource):
    ...
class SqlServerDataFeedSource(_patch.SqlServerDataFeedSource):
    ...
class DataFeedGranularity(_patch.DataFeedGranularity):
    ...
class DataFeedSchema(_patch.DataFeedSchema):
    ...
class DataFeedIngestionSettings(_patch.DataFeedIngestionSettings):
    ...

class AnomalyDetectorDirection: _metrics_advisor_client_enums.AnomalyDetectorDirection
class AnomalyIncidentStatus: _metrics_advisor_client_enums.AnomalyIncidentStatus
class AnomalySeverity: _metrics_advisor_client_enums.AnomalySeverity
class AnomalyValue: _metrics_advisor_client_enums.AnomalyValue
class ChangePointValue: _metrics_advisor_client_enums.ChangePointValue
class DataFeedAccessMode: _metrics_advisor_client_enums.DataFeedAccessMode
class DataFeedAutoRollupMethod: _metrics_advisor_client_enums.DataFeedAutoRollupMethod
class DataFeedGranularityType: _metrics_advisor_client_enums.DataFeedGranularityType
class DataFeedRollupType: _metrics_advisor_client_enums.DataFeedRollupType
class DataFeedStatus: _metrics_advisor_client_enums.DataFeedStatus
class DatasourceAuthenticationType: _metrics_advisor_client_enums.DatasourceAuthenticationType
class DatasourceCredentialType: _metrics_advisor_client_enums.DatasourceCredentialType
class DatasourceMissingDataPointFillType: _metrics_advisor_client_enums.DatasourceMissingDataPointFillType
class DatasourceType: _metrics_advisor_client_enums.DatasourceType
class DetectionConditionOperator: _metrics_advisor_client_enums.DetectionConditionOperator
class FeedbackType: _metrics_advisor_client_enums.FeedbackType
class MetricAnomalyAlertConfigurationsOperator: _metrics_advisor_client_enums.MetricAnomalyAlertConfigurationsOperator
class MetricAnomalyAlertScopeType: _metrics_advisor_client_enums.MetricAnomalyAlertScopeType
class PeriodType: _metrics_advisor_client_enums.PeriodType
class SnoozeScope: _metrics_advisor_client_enums.SnoozeScope
class AlertQueryTimeMode: _patch.AlertQueryTimeMode
