{% set name = "azure-planetarycomputer" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}

source:
  url: {{ environ.get('PLANETARYCOMPUTER_SOURCE_DISTRIBUTION', '') }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - geojson>=2.0.0
    - aiohttp
    - isodate>=0.6.1
    - pystac>=1.11.0
    - typing-extensions>=4.6.0
  run:
    - python
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - geojson>=2.0.0
    - aiohttp
    - isodate>=0.6.1
    - pystac>=1.11.0
    - typing-extensions>=4.6.0

test:
  imports:
    - azure.planetarycomputer
    - azure.planetarycomputer.aio
    - azure.planetarycomputer.models
    - azure.planetarycomputer.operations
    - azure.planetarycomputer.aio.operations

about:
  home: "https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/planetarycomputer/azure-planetarycomputer"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Microsoft Azure Planetary Computer Client Library for Python"
  description: |
    This is the Microsoft Azure Planetary Computer Client Library for Python.
    Please see https://aka.ms/azsdk/conda/releases/planetarycomputer for version details.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - jennypng
    - kashifkhan-msft
