trigger: none

pr:
  paths:
    include:
      - sdk/agentserver/

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      BuildTargetingString: azure-ai-agentserver-core|azure-ai-agentserver-invocations
      ServiceDirectory: agentserver
      TestMarkArgument: tracing_e2e
      TestTimeoutInMinutes: 60
      MatrixFilters:
        - PythonVersion=^(?!pypy3).*
      EnvVars:
        AZURE_SKIP_LIVE_RECORDING: 'true'
        AZURE_TEST_RUN_LIVE: 'true'

