trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/agentserver/

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ServiceDirectory: agentserver
      TestMarkArgument: tracing_e2e
      TestTimeoutInMinutes: 60
      EnvVars:
        AZURE_TEST_RUN_LIVE: 'true'

