#!/bin/bash

export PYTHONPATH=$PYTHONPATH:../../azure-common
export PYTHONPATH=$PYTHONPATH:../../azure-servicebus

echo "Running tests..."
which coverage &> /dev/null
if [ $? -eq 0 ]
then
        LAUNCHER='coverage run'
else
        LAUNCHER='python'
fi
$LAUNCHER -m unittest discover -p "test_servicebus_*.py"
