# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
import pytest
from azure.mgmt.deviceregistry import DeviceRegistryMgmtClient

from devtools_testutils import AzureMgmtRecordedTestCase, RandomNameResourceGroupPreparer, recorded_by_proxy

AZURE_LOCATION = "eastus"


@pytest.mark.skip("you may need to update the auto-generated test case before run it")
class TestDeviceRegistryMgmtCertificatePoliciesOperations(AzureMgmtRecordedTestCase):
    def setup_method(self, method):
        self.client = self.create_mgmt_client(DeviceRegistryMgmtClient)

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_certificate_policies_get(self, resource_group):
        response = self.client.certificate_policies.get(
            resource_group_name=resource_group.name,
            namespace_name="str",
            certificate_authority_name="str",
            certificate_policy_name="str",
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_certificate_policies_begin_create_or_replace(self, resource_group):
        response = self.client.certificate_policies.begin_create_or_replace(
            resource_group_name=resource_group.name,
            namespace_name="str",
            certificate_authority_name="str",
            certificate_policy_name="str",
            resource={
                "location": "str",
                "id": "str",
                "name": "str",
                "properties": {"certificate": {"validityPeriodInDays": 0}, "provisioningState": "str", "uuid": "str"},
                "systemData": {
                    "createdAt": "2020-02-20 00:00:00",
                    "createdBy": "str",
                    "createdByType": "str",
                    "lastModifiedAt": "2020-02-20 00:00:00",
                    "lastModifiedBy": "str",
                    "lastModifiedByType": "str",
                },
                "tags": {"str": "str"},
                "type": "str",
            },
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_certificate_policies_begin_delete(self, resource_group):
        response = self.client.certificate_policies.begin_delete(
            resource_group_name=resource_group.name,
            namespace_name="str",
            certificate_authority_name="str",
            certificate_policy_name="str",
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_certificate_policies_begin_update(self, resource_group):
        response = self.client.certificate_policies.begin_update(
            resource_group_name=resource_group.name,
            namespace_name="str",
            certificate_authority_name="str",
            certificate_policy_name="str",
            properties={"properties": {"certificate": {"validityPeriodInDays": 0}}, "tags": {"str": "str"}},
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_certificate_policies_list_by_certificate_authority(self, resource_group):
        response = self.client.certificate_policies.list_by_certificate_authority(
            resource_group_name=resource_group.name,
            namespace_name="str",
            certificate_authority_name="str",
        )
        result = [r for r in response]
        # please add some check logic here by yourself
        # ...
