#!/bin/bash

export PYTHONPATH=$PYTHONPATH:../../azure-common
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-common
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-authorization
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-cdn
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-compute
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-logic
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-network
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-notificationhubs
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-redis
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-resource
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-scheduler
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-storage
export PYTHONPATH=$PYTHONPATH:../../azure-mgmt-web
export PYTHONPATH=$PYTHONPATH:../../azure-graphrbac

echo "Running tests..."
which coverage &> /dev/null
if [ $? -eq 0 ]
then
        LAUNCHER='coverage run'
else
        LAUNCHER='python'
fi
$LAUNCHER -m unittest discover -p "test_mgmt_*.py"
