{% set name = "azure-batch" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}

source:
  url: {{ environ.get('BATCH_SOURCE_DISTRIBUTION', '') }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - aiohttp
    - isodate>=0.6.1
    - typing-extensions>=4.6.0
  run:
    - python
    - azure-core >={{ environ.get('AZURESDK_CONDA_VERSION', '0.0.0') }}
    - aiohttp
    - isodate>=0.6.1
    - typing-extensions>=4.6.0

test:
  imports:
    - azure.batch
    - azure.batch.aio
    - azure.batch.models

about:
  home: "https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/batch/azure-batch"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Microsoft Azure Batch Client Library for Python"
  description: |
    This is the Microsoft Azure Batch Client Library for Python.
    Please see https://aka.ms/azsdk/conda/releases/batch for version details.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - jennypng
    - kashifkhan-msft
