# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import SDKClient
from msrest import Serializer, Deserializer

from ._configuration import DataLakeAnalyticsAccountManagementClientConfiguration
from .operations import AccountsOperations
from .operations import DataLakeStoreAccountsOperations
from .operations import StorageAccountsOperations
from .operations import ComputePoliciesOperations
from .operations import FirewallRulesOperations
from .operations import Operations
from .operations import LocationsOperations
from . import models


class DataLakeAnalyticsAccountManagementClient(SDKClient):
    """Creates an Azure Data Lake Analytics account management client.

    :ivar config: Configuration for client.
    :vartype config: DataLakeAnalyticsAccountManagementClientConfiguration

    :ivar accounts: Accounts operations
    :vartype accounts: azure.mgmt.datalake.analytics.account.operations.AccountsOperations
    :ivar data_lake_store_accounts: DataLakeStoreAccounts operations
    :vartype data_lake_store_accounts: azure.mgmt.datalake.analytics.account.operations.DataLakeStoreAccountsOperations
    :ivar storage_accounts: StorageAccounts operations
    :vartype storage_accounts: azure.mgmt.datalake.analytics.account.operations.StorageAccountsOperations
    :ivar compute_policies: ComputePolicies operations
    :vartype compute_policies: azure.mgmt.datalake.analytics.account.operations.ComputePoliciesOperations
    :ivar firewall_rules: FirewallRules operations
    :vartype firewall_rules: azure.mgmt.datalake.analytics.account.operations.FirewallRulesOperations
    :ivar operations: Operations operations
    :vartype operations: azure.mgmt.datalake.analytics.account.operations.Operations
    :ivar locations: Locations operations
    :vartype locations: azure.mgmt.datalake.analytics.account.operations.LocationsOperations

    :param credentials: Credentials needed for the client to connect to Azure.
    :type credentials: :mod:`A msrestazure Credentials
     object<msrestazure.azure_active_directory>`
    :param subscription_id: Get subscription credentials which uniquely
     identify Microsoft Azure subscription. The subscription ID forms part of
     the URI for every service call.
    :type subscription_id: str
    :param str base_url: Service URL
    """

    def __init__(
            self, credentials, subscription_id, base_url=None):

        self.config = DataLakeAnalyticsAccountManagementClientConfiguration(credentials, subscription_id, base_url)
        super(DataLakeAnalyticsAccountManagementClient, self).__init__(self.config.credentials, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = '2016-11-01'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.accounts = AccountsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.data_lake_store_accounts = DataLakeStoreAccountsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.storage_accounts = StorageAccountsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.compute_policies = ComputePoliciesOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.firewall_rules = FirewallRulesOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.operations = Operations(
            self._client, self.config, self._serialize, self._deserialize)
        self.locations = LocationsOperations(
            self._client, self.config, self._serialize, self._deserialize)
