# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models_py3 import ArmTemplateParameter
from ._models_py3 import CodeMessageError
from ._models_py3 import CodeMessageErrorError
from ._models_py3 import ManagementAssociation
from ._models_py3 import ManagementAssociationProperties
from ._models_py3 import ManagementAssociationPropertiesList
from ._models_py3 import ManagementConfiguration
from ._models_py3 import ManagementConfigurationProperties
from ._models_py3 import ManagementConfigurationPropertiesList
from ._models_py3 import Operation
from ._models_py3 import OperationDisplay
from ._models_py3 import OperationListResult
from ._models_py3 import Solution
from ._models_py3 import SolutionPatch
from ._models_py3 import SolutionPlan
from ._models_py3 import SolutionProperties
from ._models_py3 import SolutionPropertiesList
from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "ArmTemplateParameter",
    "CodeMessageError",
    "CodeMessageErrorError",
    "ManagementAssociation",
    "ManagementAssociationProperties",
    "ManagementAssociationPropertiesList",
    "ManagementConfiguration",
    "ManagementConfigurationProperties",
    "ManagementConfigurationPropertiesList",
    "Operation",
    "OperationDisplay",
    "OperationListResult",
    "Solution",
    "SolutionPatch",
    "SolutionPlan",
    "SolutionProperties",
    "SolutionPropertiesList",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
