#!/usr/bin/env python

# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

PYLINT_ACCEPTABLE_FAILURES = [
    "azure-applicationinsights",
    "azure-batch",
    "azure-cognitiveservices-anomalydetector",
    "azure-cognitiveservices-formrecognizer",
    "azure-cognitiveservices-knowledge-nspkg",
    "azure-cognitiveservices-knowledge-qnamaker",
    "azure-cognitiveservices-language-luis",
    "azure-cognitiveservices-language-nspkg",
    "azure-cognitiveservices-language-spellcheck",
    "azure-cognitiveservices-language-textanalytics",
    "azure-cognitiveservices-nspkg",
    "azure-cognitiveservices-personalizer",
    "azure-cognitiveservices-search-autosuggest",
    "azure-cognitiveservices-search-customimagesearch",
    "azure-cognitiveservices-search-customsearch",
    "azure-cognitiveservices-search-entitysearch",
    "azure-cognitiveservices-search-imagesearch",
    "azure-cognitiveservices-search-newssearch",
    "azure-cognitiveservices-search-nspkg",
    "azure-cognitiveservices-search-videosearch",
    "azure-cognitiveservices-search-visualsearch",
    "azure-cognitiveservices-search-websearch",
    "azure-cognitiveservices-vision-computervision",
    "azure-cognitiveservices-vision-contentmoderator",
    "azure-cognitiveservices-vision-customvision",
    "azure-cognitiveservices-vision-face",
    "azure-cognitiveservices-vision-nspkg",
    "azure-common",
    "azure-nspkg",
    "azure-servicemanagement-legacy",
    "azure-graphrbac",
    "azure-loganalytics",
    "azure-servicefabric",
    "azure-template",
    "azure-keyvault",
    "azure-synapse",
    "azure-synapse-artifacts",
    "azure-synapse-spark",
    "azure-synapse-accesscontrol",
    "azure-synapse-monitoring",
    "azure-synapse-managedprivateendpoints",
    "azure-synapse-nspkg",
    "azure-ai-anomalydetector",
    "azure-security-attestation",
    "azure-iot-deviceupdate",
]
