# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from azure.identity import DefaultAzureCredential

from azure.health.deidentification import DeidentificationClient

"""
# PREREQUISITES
    pip install azure-identity
    pip install azure-health-deidentification
# USAGE
    python deidentify_documents.py

    Before run the sample, please set the values of the client ID, tenant ID and client secret
    of the AAD application as environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID,
    AZURE_CLIENT_SECRET. For more info about how to get the value, please see:
    https://docs.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal
"""


def main():
    client = DeidentificationClient(
        endpoint="ENDPOINT",
        credential=DefaultAzureCredential(),
    )

    response = client.begin_deidentify_documents(
        name="documents_smith_1",
        resource={
            "customizations": {"redactionFormat": "[{type}]", "surrogateLocale": "en-US"},
            "error": {
                "code": "FileNotFound",
                "details": [],
                "message": "File was moved after job started.",
                "target": "SourceFile",
            },
            "operation": "Redact",
            "sourceLocation": {
                "extensions": ["*"],
                "location": "https://blobtest.blob.core.windows.net/container",
                "prefix": "/documents",
            },
            "status": "NotStarted",
            "summary": {"bytesProcessed": 4096, "canceled": 0, "failed": 0, "successful": 10, "total": 10},
            "targetLocation": {
                "location": "https://blobtest.blob.core.windows.net/container",
                "overwrite": True,
                "prefix": "/documents",
            },
        },
    ).result()
    print(response)


# x-ms-original-file: 2024-11-15/DeidentifyDocuments.json
if __name__ == "__main__":
    main()
