# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .dashboard_parts_position_py3 import DashboardPartsPosition
    from .dashboard_parts_py3 import DashboardParts
    from .dashboard_lens_py3 import DashboardLens
    from .dashboard_py3 import Dashboard
    from .patchable_dashboard_py3 import PatchableDashboard
    from .resource_provider_operation_display_py3 import ResourceProviderOperationDisplay
    from .resource_provider_operation_py3 import ResourceProviderOperation
    from .error_definition_py3 import ErrorDefinition
    from .error_response_py3 import ErrorResponse, ErrorResponseException
except (SyntaxError, ImportError):
    from .dashboard_parts_position import DashboardPartsPosition
    from .dashboard_parts import DashboardParts
    from .dashboard_lens import DashboardLens
    from .dashboard import Dashboard
    from .patchable_dashboard import PatchableDashboard
    from .resource_provider_operation_display import ResourceProviderOperationDisplay
    from .resource_provider_operation import ResourceProviderOperation
    from .error_definition import ErrorDefinition
    from .error_response import ErrorResponse, ErrorResponseException
from .resource_provider_operation_paged import ResourceProviderOperationPaged
from .dashboard_paged import DashboardPaged

__all__ = [
    'DashboardPartsPosition',
    'DashboardParts',
    'DashboardLens',
    'Dashboard',
    'PatchableDashboard',
    'ResourceProviderOperationDisplay',
    'ResourceProviderOperation',
    'ErrorDefinition',
    'ErrorResponse', 'ErrorResponseException',
    'ResourceProviderOperationPaged',
    'DashboardPaged',
]
