# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class OsType(str, Enum):

    windows7 = "Windows7"
    windows_server2008 = "WindowsServer2008"
    windows_server2008_r2 = "WindowsServer2008R2"


class SupportType(str, Enum):

    supplemental_servicing = "SupplementalServicing"
    premium_assurance = "PremiumAssurance"


class ProvisioningState(str, Enum):

    succeeded = "Succeeded"
    failed = "Failed"
    canceled = "Canceled"
    accepted = "Accepted"
    provisioning = "Provisioning"
