emit:
  - "@typespec/openapi3"
  - "@azure-tools/typespec-python"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}"
    package-name: "azure-ai-responses-server"
    package-mode: "dataplane"
    flavor: "azure"
    unreferenced-types-handling: keepAll
    generate-test: false
    generate-sample: false
imports:
  - "@typespec/http"
  - "@typespec/openapi"
  - "@azure-tools/typespec-azure-core"
  - "@azure-tools/typespec-azure-core/experimental"
  - "@azure-tools/typespec-client-generator-core"
  - "@typespec/versioning"
  - "@typespec/events"
  - "@typespec/sse"
