[mypy]
ignore_missing_imports = True

# Per-module options:

# The _vendor directory holds a copy of azure-storage-blob. This package
# does not own that code, so mypy must not report errors in it.
[mypy-azure.eventhub.extensions.checkpointstoreblob._vendor.*]
ignore_errors = True
