# The MIT License (MIT)
# Copyright (c) 2025 Microsoft Corporation

from enum import Enum

try:
    # Python 3.11+
    from enum import StrEnum # type: ignore
except ImportError:
    # Python <3.11 shim                      
    class StrEnum(str, Enum):
        # keep str() stable
        def __str__(self) -> str:
            return str(self.value)
        
class CosmosRegion(StrEnum): # type: ignore
    """
    The CosmosRegion class contains the names of Azure regions that are 
    currently supported by the Azure Cosmos DB service.
    """

    AUSTRALIA_CENTRAL = "Australia Central"
    AUSTRALIA_CENTRAL_2 = "Australia Central 2"
    AUSTRALIA_EAST = "Australia East"
    AUSTRALIA_SOUTHEAST = "Australia Southeast"
    AUSTRIA_EAST = "Austria East"
    BELGIUM_CENTRAL = "Belgium Central"
    BLEU_FRANCE_CENTRAL = "Bleu France Central"
    BLEU_FRANCE_SOUTH = "Bleu France South"
    BRAZIL_SOUTH = "Brazil South"
    BRAZIL_SOUTHEAST = "Brazil Southeast"
    CANADA_CENTRAL = "Canada Central"
    CANADA_EAST = "Canada East"
    CENTRAL_INDIA = "Central India"
    CENTRAL_US = "Central US"
    CENTRAL_US_EUAP = "Central US EUAP"
    CHILE_CENTRAL = "Chile Central"
    CHINA_EAST = "China East"
    CHINA_EAST_2 = "China East 2"
    CHINA_EAST_3 = "China East 3"
    CHINA_NORTH = "China North"
    CHINA_NORTH_2 = "China North 2"
    CHINA_NORTH_3 = "China North 3"
    DELOS_CLOUD_GERMANY_CENTRAL = "Delos Cloud Germany Central"
    DELOS_CLOUD_GERMANY_NORTH = "Delos Cloud Germany North"
    DENMARK_EAST = "Denmark East"
    EAST_ASIA = "East Asia"
    EAST_US = "East US"
    EAST_US_2 = "East US 2"
    EAST_US_2_EUAP = "East US 2 EUAP"
    EAST_US_SLV = "East US SLV"
    FRANCE_CENTRAL = "France Central"
    FRANCE_SOUTH = "France South"
    GERMANY_NORTH = "Germany North"
    GERMANY_WEST_CENTRAL = "Germany West Central"
    INDONESIA_CENTRAL = "Indonesia Central"
    ISRAEL_CENTRAL = "Israel Central"
    ISRAEL_NORTHWEST = "Israel Northwest"
    ITALY_NORTH = "Italy North"
    JAPAN_EAST = "Japan East"
    JAPAN_WEST = "Japan West"
    JIO_INDIA_CENTRAL = "Jio India Central"
    JIO_INDIA_WEST = "Jio India West"
    KOREA_CENTRAL = "Korea Central"
    KOREA_SOUTH = "Korea South"
    MALAYSIA_SOUTH = "Malaysia South"
    MALAYSIA_WEST = "Malaysia West"
    MEXICO_CENTRAL = "Mexico Central"
    NEW_ZEALAND_NORTH = "New Zealand North"
    NORTH_CENTRAL_US = "North Central US"
    NORTH_EUROPE = "North Europe"
    NORWAY_EAST = "Norway East"
    NORWAY_WEST = "Norway West"
    POLAND_CENTRAL = "Poland Central"
    QATAR_CENTRAL = "Qatar Central"
    SOUTH_AFRICA_NORTH = "South Africa North"
    SOUTH_AFRICA_WEST = "South Africa West"
    SOUTH_CENTRAL_US = "South Central US"
    SOUTH_CENTRAL_US_2 = "South Central US 2"
    SOUTH_INDIA = "South India"
    SOUTHEAST_ASIA = "Southeast Asia"
    SOUTHEAST_US = "Southeast US"
    SOUTHEAST_US_3 = "Southeast US 3"
    SOUTHEAST_US_5 = "Southeast US 5"
    SOUTHWEST_US = "Southwest US"
    SPAIN_CENTRAL = "Spain Central"
    SWEDEN_CENTRAL = "Sweden Central"
    SWEDEN_SOUTH = "Sweden South"
    SWITZERLAND_NORTH = "Switzerland North"
    SWITZERLAND_WEST = "Switzerland West"
    TAIWAN_NORTH = "Taiwan North"
    TAIWAN_NORTHWEST = "Taiwan Northwest"
    UAE_CENTRAL = "UAE Central"
    UAE_NORTH = "UAE North"
    UK_SOUTH = "UK South"
    UK_WEST = "UK West"
    USDOD_CENTRAL = "USDoD Central"
    USDOD_EAST = "USDoD East"
    USGOV_ARIZONA = "USGov Arizona"
    USGOV_TEXAS = "USGov Texas"
    USGOV_VIRGINIA = "USGov Virginia"
    USNAT_EAST = "USNat East"
    USNAT_WEST = "USNat West"
    USSEC_EAST = "USSec East"
    USSEC_WEST = "USSec West"
    USSEC_WEST_CENTRAL = "USSec West Central"
    WEST_CENTRAL_US = "West Central US"
    WEST_EUROPE = "West Europe"
    WEST_INDIA = "West India"
    WEST_US = "West US"
    WEST_US_2 = "West US 2"
    WEST_US_3 = "West US 3"
