# The MIT License (MIT)
# Copyright (c) Microsoft Corporation. All rights reserved.
"""Concrete cursor type; other extension exports retain their dynamic boundary."""

from typing import Any

def _validate_runtime_configuration(config: Any = None) -> None: ...

class _ItemFeedCursor:
    def __init__(self) -> None: ...
    @property
    def has_more(self) -> bool: ...
    @property
    def continuation_supported(self) -> bool: ...
    @property
    def can_retry_setup(self) -> bool: ...

def __getattr__(name: str) -> Any: ...
