# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft and contributors.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class JobStatistics(Model):
    """
    The Data Lake Analytics U-SQL job execution statistics.

    :param last_update_time_utc: Gets the last update time for the statistics.
    :type last_update_time_utc: datetime
    :param stages: Gets the list of stages for the job.
    :type stages: list of :class:`JobStatisticsVertexStage
     <datalakeanalyticsjobmanagementclient.models.JobStatisticsVertexStage>`
    """ 

    _attribute_map = {
        'last_update_time_utc': {'key': 'lastUpdateTimeUtc', 'type': 'iso-8601'},
        'stages': {'key': 'stages', 'type': '[JobStatisticsVertexStage]'},
    }

    def __init__(self, last_update_time_utc=None, stages=None):
        self.last_update_time_utc = last_update_time_utc
        self.stages = stages
