name: GitHub Actions - Test

on:
  push:
    branches:
      - main
    paths:
      - .github/**
  pull_request:
    paths:
      - .github/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        folder: [.github, .github/shared]
        os: [ubuntu, windows]

    runs-on: ${{ fromJSON('{"ubuntu":"ubuntu-24.04", "windows":"windows-2022"}')[matrix.os] }}

    defaults:
      run:
        working-directory: ./${{ matrix.folder }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github

      - if: ${{ matrix.folder == '.github' }}
        name: Install dependencies for github-script actions
        uses: ./.github/actions/install-deps-github-script

      - if: ${{ matrix.folder == '.github' }}
        name: Verify all modules are importable
        uses: actions/github-script@v8
        with:
          script: |
            const { join } = await import("path");
            const { pathToFileURL } = await import("url");
            const fullPath = join(process.env.GITHUB_WORKSPACE, ".github", "workflows", "src", "github-test.js");
            const { default: importAllModules } = await import(pathToFileURL(fullPath).href);
            await importAllModules({ core });

      - name: Install dev deps
        uses: ./.github/actions/setup-node-install-deps
        with:
          # actions/github-script@v8 uses Node 24
          node-version: 24.x
          working-directory: ./${{ matrix.folder }}

      - run: npm run test:ci

      - run: npm run lint

      - run: npm run format:check:ci
