name: After APIView

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  post-apiview:
    name: After APIView
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: "eng/common"

      - name: Create APIView Comment on PR
        run: |
          . "eng/common/scripts/Helpers/ApiView-Helpers.ps1"
          Set-ApiViewCommentForRelatedIssues -HeadCommitish ${{ github.event.pull_request.head.sha }} -AuthToken ${{ secrets.GITHUB_TOKEN }} -GitHubActionRunUrl $env:GITHUB_ACTION_RUN_URL
        shell: pwsh
        env:
          GITHUB_ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
