trigger: none

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      BuildTargetingString: azure*
      ServiceDirectory: webpubsub
      MatrixReplace:
        - TestSamples=.*/true
      EnvVars:
        AZURE_TEST_RUN_LIVE: "true" # use when utilizing the New-TestResources Script
