trigger: none

parameters:
  - name: Services
    type: object
    default:
      - azure-mgmt-webpubsub
      - azure-messaging-webpubsubservice
      - azure-messaging-webpubsubclient

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ServiceDirectory: webpubsub
      Packages: ${{ parameters.Services }}
      MatrixReplace:
        - TestSamples=.*/true
      EnvVars:
        AZURE_TEST_RUN_LIVE: "true" # use when utilizing the New-TestResources Script
