# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------

"""Merged models from both Workspace and Bookshelf sub-clients."""

from ._workspace.azure.ai.discovery.models import (  # type: ignore
    ByType,
    ComputeUsage,
    Conversation,
    DiscoveryEngine,
    DiscoveryEngineStatus,
    DiscoveryEngineUpdate,
    ExecutionHistoryEntry,
    InfraOverrides,
    InlineFile,
    InputDataMount,
    Investigation,
    InvestigationStatus,
    NodepoolUsage,
    Operation,
    OperationState,
    OperationStatusRunResultError,
    OutputDataMount,
    OutputDataUri,
    PagedOperation,
    PagedWorkingMemoryEntry,
    ResourceOperationStatusInvestigationInvestigationError,
    RunRequestEnvironmentVariable,
    RunResult,
    RunResultToolReport,
    RunStatus,
    StartTaskRequest,
    SupercomputerUsage,
    Tag,
    Task,
    TaskAssignee,
    TaskComment,
    TaskPriority,
    TaskResult,
    TaskStatus,
    WorkingMemoryEntry,
    WorkingMemoryEntryType,
)
from ._bookshelf.azure.ai.discovery.models import (  # type: ignore
    IndexingStatus,
    KnowledgeBase,
    KnowledgeBaseOperationStatus,
    KnowledgeBaseVersion,
    ProvisioningState,
    RepeatabilityResult,
    StorageAssetReference,
)

__all__ = [
    # Workspace models
    "ByType",
    "ComputeUsage",
    "Conversation",
    "DiscoveryEngine",
    "DiscoveryEngineStatus",
    "DiscoveryEngineUpdate",
    "ExecutionHistoryEntry",
    "InfraOverrides",
    "InlineFile",
    "InputDataMount",
    "Investigation",
    "InvestigationStatus",
    "NodepoolUsage",
    "Operation",
    "OperationState",
    "OperationStatusRunResultError",
    "OutputDataMount",
    "OutputDataUri",
    "PagedOperation",
    "PagedWorkingMemoryEntry",
    "ResourceOperationStatusInvestigationInvestigationError",
    "RunRequestEnvironmentVariable",
    "RunResult",
    "RunResultToolReport",
    "RunStatus",
    "StartTaskRequest",
    "SupercomputerUsage",
    "Tag",
    "Task",
    "TaskAssignee",
    "TaskComment",
    "TaskPriority",
    "TaskResult",
    "TaskStatus",
    "WorkingMemoryEntry",
    "WorkingMemoryEntryType",
    # Bookshelf models
    "IndexingStatus",
    "KnowledgeBase",
    "KnowledgeBaseOperationStatus",
    "KnowledgeBaseVersion",
    "ProvisioningState",
    "RepeatabilityResult",
    "StorageAssetReference",
]
